language: cpp
sudo: required

install:
  - curl http://ubuntu.openturns.org/openturns.org-repo.key | sudo apt-key add -
  - echo deb http://ubuntu.openturns.org precise main | sudo tee /etc/apt/sources.list.d/openturns.list
  - sudo apt-get update
  - sudo apt-get -y install python-sphinx 
  - sudo pip install numpydoc alabaster pytest

script:
  - python setup.py install --user
  - py.test tests/
  - cd doc && make html BUILDDIR=~/.local/share/ottemplate/doc